server:
  port: 8080

spring:
  application:
    name: dating-platform

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dating_platform?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

    # Redis配置
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dating.entity
  configuration:
    map-underscore-to-camel-case: true

# JWT配置
jwt:
  secret: Guvq8DqKB97ZBJetumfPDUvmoYxjw/Qr1j2PtvogOYc334LOr/AW3sw8ZWNq28HJwy3MsofB9/7zMLvjUwRjXg==
  expire: 86400000 # 24小时

# 文件上传配置
file:
  upload-path: /uploads/
  domain: http://localhost:8080

logging:
  level:
    com.dating.mapper: debug

# MinIO 配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: dating-platform
  public-read: true  # 开发环境true，生产环境false